### ISSUE TITLE
Request executed twice

### ISSUE THREAD

**Issue by gambolputty** [moritzsternemann/vue-plausible#3]
Hello!

In my Nuxt app the request to `/api/event` is emitted twice.
The first request is targeted at my custom host defined in the `apiHost` property in `nuxt.config.js` (self-hosted Plausible instance). The second one is sent to `https://plausible.io/api/event`. Is this intentional?

This code is executed in my layout file when mounted:

```js
    const { enableAutoPageviews } = Plausible()

    // This tracks the current page view and all future ones as well
    enableAutoPageviews()
```

![image](https://user-images.githubusercontent.com/8270488/103160855-ec211b00-47d9-11eb-979d-5e8f2434a2e1.png)

**Comment by moritzsternemann** [comment]
Hey @gambolputty!

When you call `Plausible()` like in you snippet, a new instance of the plausible tracker is created with the default settings.

The event duplication is then caused by having two instances of the tracker, one with your `apiHost`, created by the Nuxt module and configured in `nuxt.config.js`. The second instance is initialized by the call in your layout file.

If you want to access the plausible tracker instance in any of you components, including layouts, I suggest to use the properties explained in [the Usage section of the README](https://github.com/moritzsternemann/vue-plausible#usage-1).

**Comment by gambolputty** [comment]
My mistake. Thanks for clarifying! 
Will close this issue now.

**Comment by kernoeb** [comment]
Hello!
I'm having the same issue in Nuxt.js too (with default SSR), except that I only use the `nuxt.config.js` configuration, I don't call it somewhere else :thinking: 

```js
modules: [
  'vue-plausible'
],

plausible: {
  apiHost: 'https://plausible.example.com'
},
```

Any idea ?
Thanks!
